name: Publish

on: push
# on:
#   workflow_dispatch:
#   workflow_run:
#     workflows:
#       - Test
#     branches:
#       - alpha
#       - beta
#       - next
#       - main
#     types:
#       - completed

jobs:
  publish:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    # permissions:
    #   contents: write
    #   issues: write
    #   pull-requests: write
    #   id-token: write

    # if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0
        #   ref: ${{ github.event.workflow_run.head_branch || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Packages
        run: yarn install

      - name: Install Flatpak
        run: sudo apt-get install -y flatpak flatpak-builder elfutils
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Publish
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
