name: Publish

on:
  push:
    branches:
      - main
      - beta
      - demo
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
      - .yarnrc
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
      - .yarnrc
      - LICENSE

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-next-version:
    uses: ./.github/workflows/get-next-version.yml
    with:
      ref: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  create-draft-release:
    uses: ./.github/workflows/create-draft-release.yml
    needs:
      - get-next-version
    if: needs.get-next-version.outputs.published == 'true'
    with:
      notes: ${{ needs.get-next-version.outputs.notes }}
      version: ${{ needs.get-next-version.outputs.version }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-electron-app:
    uses: ./.github/workflows/build-electron-app.yml
    needs:
      - get-next-version
      - create-draft-release
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    with:
      operatingSystem: ${{ matrix.os }}
      version: ${{ needs.get-next-version.outputs.version }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  publish-github-release:
    uses: ./.github/workflows/publish-github-release.yml
    needs:
      - create-draft-release
      - build-electron-app
    with:
      repo: ${{ github.repository }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  publish-to-steam:
    uses: ./.github/workflows/publish-to-steam.yml
    needs:
      - get-next-version
      - publish-github-release
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        include:
          - os: macos-latest
            platformAlias: darwin
          - os: ubuntu-latest
            platformAlias: linux
          - os: windows-latest
            platformAlias: win32
    with:
      branch: ${{ github.ref_name }}
      platformAlias: ${{ matrix.platformAlias }}
      operatingSystem: ${{ matrix.os }}
      steamReleaseBranch: ${{ github.ref_name == 'beta' && 'beta' || 'prerelease' }}
      version: ${{ needs.get-next-version.outputs.version }}
      zipName: The.Inn.at.Nightfall-${{ matrix.platformAlias }}-x64-${{ needs.get-next-version.outputs.version }}.zip
    secrets:
      steamAppID: ${{ secrets.STEAM_APP_ID }}
      steamBuildUsername: ${{ secrets.STEAM_BUILD_USERNAME }}
      steamBuildConfigVDF: ${{ secrets.STEAM_BUILD_CONFIG_VDF }}
      steamDemoAppID: ${{ secrets.STEAM_DEMO_APP_ID }}
      token: ${{ secrets.GITHUB_TOKEN }}
